version: '3'

services:
  backend:
    build:
      context: ./treenote-backend
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/treenote
      - SPRING_DATASOURCE_USERNAME=treenote
      - SPRING_DATASOURCE_PASSWORD=contrasena-extra-segura
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./treenote-backend/:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  db:
    image: 'postgres:13-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=treenote
      - POSTGRES_PASSWORD=contrasena-extra-segura
